name: Push to release branches
on:
  push:
    branches:
      - "main"
      - "release/v*"
env:
  COMMIT: ${{ github.sha }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE: ${{ github.repository_owner }}/rancher
  IMAGE_AGENT: ${{ github.repository_owner }}/rancher-agent
  IMAGE_INSTALLER: ${{ github.repository_owner }}/system-agent-installer-rancher
  REGISTRY: "docker.io"
jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
  build-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [s390x]
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup and build
        uses: ./.github/actions/build-images/server
  build-agent:
    strategy:
      matrix:
        os: [linux]
        arch: [s390x]
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup and build
        uses: ./.github/actions/build-images/agent
  # COMMENTED OUT: Uncomment when s390x environment is available
  # integration-tests:
  #   needs: [build-server, build-agent]
  #   with:
  #     parent_run_id: ${{ github.run_id }}
  #   uses: ./.github/workflows/integration-tests.yml
  push-images:
    # needs: [unit-tests, integration-tests]
    needs: [unit-tests, build-server, build-agent]
    strategy:
      matrix:
        os: [linux]
        arch: [s390x]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write # Added permission for ghcr.io
    env:
      ARCH: ${{ matrix.arch }}
      OS: ${{ matrix.os }}
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY: ghcr.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: push
        uses: ./.github/actions/push-images
